---
# create mysql vm
- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{resource_group_name}}"
    name: "{{my_nic}}"
    virtual_network: "{{vnet_name}}"
    subnet: "{{subnet_name}}"
    public_ip: no
    security_group: "{{nsg_name}}"
    private_ip_allocation_method: Static
    private_ip_address: "{{private_ip}}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{resource_group_name}}"
    name: "{{vm_name}}"
    vm_size: "{{vm_size}}"
    os_disk_size_gb: 60
    managed_disk_type: "{{vm_plan}}"
    admin_username: "{{admin_user}}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "{{ authkeys }}"
        key_data: "{{ key_data }}"
    network_interfaces: "{{my_nic}}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.6'
      version: latest

- name: Create SSH config file
  file:
    path: "{{ config }}"
    mode: 0644
    state: touch

- name: Add VM connection to the SSH config
  blockinfile:
    dest: "{{ config }}"
    marker: "# {mark} {{ marker }}"
    block: |
      Host {{ sshname }}
        User {{admin_user}}
        StrictHostKeyChecking no
        IdentityFile {{ sshkey }}
        Hostname {{ private_ip }}
        Port 22
  tags: ip

