---
# tasks file for ansible-jenkins
- include: create-vm.yml
  tags: create

- include: add-disks.yml
  tags: addisk

- include: disk-mgmt.yml
  tags: mgmtdisk

- include: nsg-setup.yml
  tags: nsg

- include: reboot-vm.yml
  tags: reboot

#- include: rm-disk.yml
#  tags: rmdisk

